site_name: ITニュース一覧ページ
site_url: https://github.com/rooope329/automation_project
repo_url: https://github.com/rooope329/automation_project
repo_name: rooope329/automation_project  # リンクの横に表示されるテキスト
docs_dir: src/data

theme:
  name: material
  language: ja  
  palette:
    - primary: indigo
      accent: light blue
  featres:
    - navigation.sections

#  pluginsの機能設定
plugins:
  - search:
      lang: ja
  - awesome-pages:
      filename: .pages
      collapse_single_pages: False

extra_css:
  - stylesheets/extra.css

