services:
  automation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - PYTHONPATH=/app
    container_name: automation
    ipc: host
    init: true
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
    env_file:
      - ../.env
    tty: true
    stdin_open: true
      
